### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Philwh** [SeydX/homebridge-sonybravia-platform#1] opened 2018-02-13 20:53 UTC
Im having this problem when running homebridge.

Any help would be appreciated

[2/13/2018, 8:47:13 PM] [Sony Bravia] Initializing SonyBravia platform...
/usr/local/lib/node_modules/homebridge-sonybravia-platform/index.js:756
    this.tvSwitch = self.tvSwitch;
                    ^

ReferenceError: self is not defined
    at new TVSwitchAccessory (/usr/local/lib/node_modules/homebridge-sonybravia-platform/index.js:756:21)
    at async.waterfall.reqApps.token (/usr/local/lib/node_modules/homebridge-sonybravia-platform/index.js:131:36)
    at nextTask (/usr/local/lib/node_modules/homebridge-sonybravia-platform/node_modules/async/dist/async.js:5310:14)
    at Object.waterfall (/usr/local/lib/node_modules/homebridge-sonybravia-platform/node_modules/async/dist/async.js:5320:5)
    at Object.accessories (/usr/local/lib/node_modules/homebridge-sonybravia-platform/index.js:117:12)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by seydx** [comment] 2018-02-13 21:07
hello, have you installed the latest version? and can you post your config pls

**Comment by Philwh** [comment] 2018-02-13 21:45
Yes only installed today. I assume you mean config.json...

I haven't bothered putting and cec or apps in there yet until i get it setup ok.
Also i have left the "homeapp" the same as your example because the curl commands in your instructions wouldn't work for me. Im quite new to this terminal stuff.

    "platforms": [
      {
        "platform":"SonyBravia",
        "name":"Sony Bravia",
        "ipadress":"192.168.1.2",
        "psk":"****",
        "homeapp":"com.sony.dtv.eu.siptv.video.eu.siptv.atv.MainActivity",
        "tvSwitch": true,
        "polling":true,
        "interval": 2
        }

    ]

**Comment by seydx** [comment] 2018-02-14 02:10
Should be fixed with https://github.com/SeydX/homebridge-sonybravia-platform/commit/0009bccb0755333ab48e1ca8e4a5144b1f312b76

please update to latest version

sudo npm install -g homebridge-sonybravia-platform@latest

**Comment by seydx** [comment] 2018-02-14 07:04
Version 1.2.0 is out. Please check your config json file if you update to v 1.2.0
You dont need anymore the "tvSwitch" in the config

**Comment by Philwh** [comment] 2018-02-14 08:55
Thanks for your help its now working.

**Comment by Philwh** [comment] 2018-02-14 13:23
Sorry to bug you again, but I'm trying to add 2 more sony tvs to this platform and the config works ok but keep getting this in the homebridge output. 


[2/14/2018, 1:17:52 PM] [Sony Loft 1] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:17:52 PM] [Sony Loft 1] Fetching Source Input failed - Trying again...
[2/14/2018, 1:17:52 PM] [Sony Loft 2] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:17:52 PM] [Sony Loft 2] Fetching Source Input failed - Trying again...
[2/14/2018, 1:18:03 PM] [Sony Loft 1] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:18:03 PM] [Sony Loft 1] Fetching Source Input failed - Trying again...
[2/14/2018, 1:18:03 PM] [Sony Loft 2] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:18:03 PM] [Sony Loft 2] Fetching Source Input failed - Trying again...
[2/14/2018, 1:18:13 PM] [Sony Loft 1] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:18:13 PM] [Sony Loft 1] Fetching Source Input failed - Trying again...
[2/14/2018, 1:18:14 PM] [Sony Loft 2] Could not retrieve Source Inputs, error:Error: Callback was already called.
[2/14/2018, 1:18:14 PM] [Sony Loft 2] Fetching Source Input failed - Trying again...

**Comment by seydx** [comment] 2018-02-14 13:50
Thanks for feedback. The problem is that the accessories like TV Switch dont have unique names (because the plugin dont support multiple platforms yet) to generate UUID.

I will fix that

**Comment by seydx** [comment] 2018-02-14 14:38
v1.2.1 is out, update to latest version please

**Comment by seydx** [comment] 2018-02-14 14:41
And update your config.json please, give the platform unique names, you can change the names later in the Home App

**Comment by Philwh** [comment] 2018-02-14 15:03
Awesome Thanks

**Comment by seydx** [comment] 2018-02-14 15:05
Ah there is a Problem with the hdmi/cec names, 1.2.2 is on the way

**Comment by seydx** [comment] 2018-02-14 15:10
1.2.2 is out. Have fun

**Closed as completed by seydx** 2018-02-14 15:10 UTC
Labels: bug

**Comment by Philwh** [comment] 2018-03-22 11:58
I have been keeping up with your updates lately and now i keep getting the following errors over and over causing Homebridge to fail to start properly

[3/22/2018, 11:55:41 AM] [Lounge TV] Getting inputs...
[3/22/2018, 11:55:41 AM] [Lounge TV] Found 4 HDMI inputs with 2 inserted CEC devices
[3/22/2018, 11:55:41 AM] [Lounge TV] Lounge TV: Error: Callback was already called. - Trying again
[3/22/2018, 11:55:46 AM] [Sony Loft 1] Getting inputs...
[3/22/2018, 11:55:46 AM] [Sony Loft 2] Getting inputs...
[3/22/2018, 11:55:46 AM] [Sony Loft 1] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 11:55:46 AM] [Sony Loft 1] Sony Loft 1: Error: Callback was already called. - Trying again
[3/22/2018, 11:55:46 AM] [Sony Loft 2] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 11:55:46 AM] [Sony Loft 2] Sony Loft 2: Error: Callback was already called. - Trying again

My config for the tv's 

"platforms": [
      {
        "platform":"SonyBravia",
        "name":"Lounge TV",
        "ipadress":"192.168.1.2",
        "mac":"10:4f:a8:91:a5:79",
        "psk":"****",
        "extraInputs":false,
        "appsEnabled":false,
        "homeapp":"com.sony.dtv.com.sony.dtv.tvx.com.sony.dtv.tvx.MainActivity",
        "interval": 15,
        "volumeEnabled":true,
        "maxVolume":30,
        "cecs":
        [
          {
            "label":"Apple TV",
            "logaddr":8,"port":3
          },
          {
            "label":"PlayStation 4",
            "logaddr":4,"port":4
          }
        ]
      },
      {
        "platform":"SonyBravia",
        "name":"Sony Loft 1",
        "ipadress":"192.168.1.6",
        "mac":"10:4f:a8:54:c2:85",
        "psk":"****",
        "extraInputs":false,
        "appsEnabled":false,
        "homeapp":"com.sony.dtv.com.sony.dtv.tvx.com.sony.dtv.tvx.MainActivity",
        "interval": 15,
        "volumeEnabled":true,
        "maxVolume":30
      },
      {
        "platform":"SonyBravia",
        "name":"Sony Loft 2",
        "ipadress":"192.168.1.9",
        "mac":"10:4f:a8:4a:a4:55",
        "psk":"****",
        "extraInputs":false,
        "appsEnabled":false,
        "homeapp":"com.sony.dtv.com.sony.dtv.tvx.com.sony.dtv.tvx.MainActivity",
        "interval":15,
        "volumeEnabled":true,
        "maxVolume":30
      }

**Comment by seydx** [comment] 2018-03-22 12:43
Hey, do you have installed the latest version??

**Comment by Philwh** [comment] 2018-03-22 13:23
Yes i do, installed the latest version this morning

**Comment by seydx** [comment] 2018-03-22 13:24
Can you attach your full Log here please

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________

**Comment by Philwh** [comment] 2018-03-22 13:35
That link just sends me to the download page for microsoft outlook mobile app.

**Comment by seydx** [comment] 2018-03-22 13:37
hehe no, can you post your full log after restart here please

**Comment by Philwh** [comment] 2018-03-22 13:42
[3/22/2018, 1:40:44 PM] Loaded plugin: homebridge-magichome
homebridge API version: 2.2
[3/22/2018, 1:40:44 PM] Registering accessory 'homebridge-magichome.MagicHome'
[3/22/2018, 1:40:44 PM] ---
[3/22/2018, 1:40:44 PM] Loaded plugin: homebridge-sonybravia-platform
[3/22/2018, 1:40:44 PM] Registering platform 'homebridge-sonybravia-platform.SonyBravia'
[3/22/2018, 1:40:44 PM] ---
[3/22/2018, 1:40:45 PM] Loaded plugin: homebridge-wifi370-led-controller
[3/22/2018, 1:40:45 PM] Registering accessory 'homebridge-wifi370-led-controller.wifi370'
[3/22/2018, 1:40:45 PM] ---
[3/22/2018, 1:40:45 PM] Loaded config.json with 2 accessories and 3 platforms.
[3/22/2018, 1:40:45 PM] ---
[3/22/2018, 1:40:45 PM] Loading 3 platforms...
[3/22/2018, 1:40:45 PM] [Lounge TV] Initializing SonyBravia platform...
[3/22/2018, 1:40:45 PM] [Lounge TV] Getting apps...
[3/22/2018, 1:40:45 PM] [Sony Loft 1] Initializing SonyBravia platform...
[3/22/2018, 1:40:45 PM] [Sony Loft 1] Getting apps...
[3/22/2018, 1:40:45 PM] [Sony Loft 2] Initializing SonyBravia platform...
[3/22/2018, 1:40:45 PM] [Sony Loft 2] Getting apps...
[3/22/2018, 1:40:45 PM] Loading 2 accessories...
[3/22/2018, 1:40:45 PM] [Led Strip] Initializing MagicHome accessory...
[3/22/2018, 1:40:45 PM] [Top lights] Initializing wifi370 accessory...
[3/22/2018, 1:40:45 PM] [Lounge TV] Found 41 apps!
[3/22/2018, 1:40:45 PM] [Lounge TV] Getting inputs...
[3/22/2018, 1:40:45 PM] [Lounge TV] Found 4 HDMI inputs with 2 inserted CEC devices
[3/22/2018, 1:40:45 PM] [Lounge TV] Initializing platform accessory 'Lounge TV Power'...
[3/22/2018, 1:40:45 PM] [Lounge TV] Initializing platform accessory 'Lounge TV Apps'...
[3/22/2018, 1:40:45 PM] [Lounge TV] Initializing platform accessory 'Lounge TV HDMI 1'...
[3/22/2018, 1:40:45 PM] [Lounge TV] Lounge TV: ReferenceError: self is not defined - Trying again
[3/22/2018, 1:40:45 PM] [Top lights] Version check for homebridge-wifi370-led-controller
[3/22/2018, 1:40:45 PM] [Top lights] npm version is 1.1.5, your local version is 1.1.5
[3/22/2018, 1:40:45 PM] [Lounge TV] Following, a list of all installed Apps on the TV. Have fun.
[3/22/2018, 1:40:45 PM] [Lounge TV] 0: Play Store
[3/22/2018, 1:40:45 PM] [Lounge TV] 1: YouTube
[3/22/2018, 1:40:45 PM] [Lounge TV] 2: Album
[3/22/2018, 1:40:45 PM] [Lounge TV] 3: Music
[3/22/2018, 1:40:45 PM] [Lounge TV] 4: Programme Guide
[3/22/2018, 1:40:45 PM] [Lounge TV] 5: Recorded Title List
[3/22/2018, 1:40:45 PM] [Lounge TV] 6: Aerial Dream
[3/22/2018, 1:40:45 PM] [Lounge TV] 7: IP Cam Viewer Lite
[3/22/2018, 1:40:45 PM] [Lounge TV] 8: Twitch
[3/22/2018, 1:40:45 PM] [Lounge TV] 9: Amazon Video
[3/22/2018, 1:40:45 PM] [Lounge TV] 10: Asphalt Nitro
[3/22/2018, 1:40:45 PM] [Lounge TV] 11: Play Music
[3/22/2018, 1:40:45 PM] [Lounge TV] 12: Play Games
[3/22/2018, 1:40:45 PM] [Lounge TV] 13: Play Movies &amp; TV
[3/22/2018, 1:40:45 PM] [Lounge TV] 14: Netflix
[3/22/2018, 1:40:45 PM] [Lounge TV] 15: Internet Browser
[3/22/2018, 1:40:45 PM] [Lounge TV] 16: Video
[3/22/2018, 1:40:45 PM] [Lounge TV] 17: Photo Sharing Plus
[3/22/2018, 1:40:45 PM] [Lounge TV] 18: TV Control Setup with Amazon Alexa
[3/22/2018, 1:40:45 PM] [Lounge TV] 19: PlayStation Video
[3/22/2018, 1:40:45 PM] [Lounge TV] 20: Screen mirroring
[3/22/2018, 1:40:45 PM] [Lounge TV] 21: Plex
[3/22/2018, 1:40:45 PM] [Lounge TV] 22: HDHomeRun
[3/22/2018, 1:40:45 PM] [Lounge TV] 23: Kodi
[3/22/2018, 1:40:45 PM] [Lounge TV] 24: YouView
[3/22/2018, 1:40:45 PM] [Lounge TV] 25: BBC iPlayer
[3/22/2018, 1:40:45 PM] [Lounge TV] 26: ITV Player
[3/22/2018, 1:40:45 PM] [Lounge TV] 27: All 4
[3/22/2018, 1:40:45 PM] [Lounge TV] 28: Demand 5
[3/22/2018, 1:40:45 PM] [Lounge TV] 29: BBC News
[3/22/2018, 1:40:45 PM] [Lounge TV] 30: BBC Sport
[3/22/2018, 1:40:45 PM] [Lounge TV] 31: 500px
[3/22/2018, 1:40:45 PM] [Lounge TV] 32: Digital Concert Hall
[3/22/2018, 1:40:45 PM] [Lounge TV] 33: Activate Enhanced Features
[3/22/2018, 1:40:45 PM] [Lounge TV] 34: Wuaki.tv
[3/22/2018, 1:40:45 PM] [Lounge TV] 35: Qello Concerts
[3/22/2018, 1:40:45 PM] [Lounge TV] 36: GREEN.TV
[3/22/2018, 1:40:45 PM] [Lounge TV] 37: uStudio
[3/22/2018, 1:40:45 PM] [Lounge TV] 38: Meteonews TV
[3/22/2018, 1:40:45 PM] [Lounge TV] 39: Tagesschau
[3/22/2018, 1:40:45 PM] [Lounge TV] 40: DW for Smart TV
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Found 40 apps!
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Getting inputs...
[3/22/2018, 1:40:46 PM] [Sony Loft 1] Found 38 apps!
[3/22/2018, 1:40:46 PM] [Sony Loft 1] Getting inputs...
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Initializing platform accessory 'Sony Loft 2 Power'...
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Initializing platform accessory 'Sony Loft 2 Apps'...
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Initializing platform accessory 'Sony Loft 2 HDMI 1'...
[3/22/2018, 1:40:46 PM] [Sony Loft 2] Sony Loft 2: ReferenceError: self is not defined - Trying again
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Initializing platform accessory 'Sony Loft 1 Power'...
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Initializing platform accessory 'Sony Loft 1 Apps'...
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Initializing platform accessory 'Sony Loft 1 HDMI 1'...
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Sony Loft 1: ReferenceError: self is not defined - Trying again
[3/22/2018, 1:40:47 PM] [Sony Loft 2] Following, a list of all installed Apps on the TV. Have fun.
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 0: Album
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 1: Music
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 2: Programme Guide
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 3: Recorded Title List
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 4: YouTube
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 5: Play Store
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 6: Twitch
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 7: Amazon Video
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 8: Games Shop
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 9: PlayStation Video
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 10: Photo Sharing Plus
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 11: Screen mirroring
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 12: Video
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 13: Internet Browser
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 14: Play Music
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 15: Play Games
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 16: Play Movies &amp; TV
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 17: Netflix
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 18: HDHomeRun
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 19: Kodi
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 20: Plex
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 21: TuneIn Radio
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 22: Asphalt 8
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 23: YouView
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 24: BBC iPlayer
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 25: ITV Player
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 26: All 4
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 27: Demand 5
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 28: BBC News
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 29: BBC Sport
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 30: 500px
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 31: Digital Concert Hall
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 32: Activate Enhanced Features
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 33: Wuaki.tv
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 34: Qello Concerts
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 35: GREEN.TV
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 36: uStudio
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 37: Meteonews TV
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 38: Tagesschau
[3/22/2018, 1:40:47 PM] [Sony Loft 2] 39: DW for Smart TV
[3/22/2018, 1:40:47 PM] [Sony Loft 1] Following, a list of all installed Apps on the TV. Have fun.
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 0: Album
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 1: Music
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 2: Programme Guide
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 3: Recorded Title List
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 4: Play Store
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 5: YouTube
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 6: Twitch
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 7: Amazon Video
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 8: Games Shop
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 9: PlayStation Video
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 10: Photo Sharing Plus
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 11: Screen mirroring
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 12: Video
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 13: Internet Browser
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 14: Play Music
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 15: Play Games
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 16: Play Movies &amp; TV
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 17: Netflix
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 18: Kodi
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 19: HDHomeRun
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 20: Plex
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 21: YouView
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 22: BBC iPlayer
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 23: ITV Player
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 24: All 4
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 25: Demand 5
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 26: BBC News
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 27: BBC Sport
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 28: 500px
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 29: Digital Concert Hall
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 30: Activate Enhanced Features
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 31: Wuaki.tv
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 32: Qello Concerts
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 33: GREEN.TV
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 34: uStudio
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 35: Meteonews TV
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 36: Tagesschau
[3/22/2018, 1:40:47 PM] [Sony Loft 1] 37: DW for Smart TV
[3/22/2018, 1:40:55 PM] [Lounge TV] Getting inputs...
[3/22/2018, 1:40:55 PM] [Lounge TV] Found 4 HDMI inputs with 2 inserted CEC devices
[3/22/2018, 1:40:55 PM] [Lounge TV] Lounge TV: Error: Callback was already called. - Trying again
[3/22/2018, 1:40:56 PM] [Sony Loft 2] Getting inputs...
[3/22/2018, 1:40:57 PM] [Sony Loft 1] Getting inputs...
[3/22/2018, 1:40:57 PM] [Sony Loft 2] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:40:57 PM] [Sony Loft 2] Sony Loft 2: Error: Callback was already called. - Trying again
[3/22/2018, 1:40:57 PM] [Sony Loft 1] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:40:57 PM] [Sony Loft 1] Sony Loft 1: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:05 PM] [Lounge TV] Getting inputs...
[3/22/2018, 1:41:06 PM] [Lounge TV] Found 4 HDMI inputs with 2 inserted CEC devices
[3/22/2018, 1:41:06 PM] [Lounge TV] Lounge TV: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:07 PM] [Sony Loft 2] Getting inputs...
[3/22/2018, 1:41:07 PM] [Sony Loft 1] Getting inputs...
[3/22/2018, 1:41:07 PM] [Sony Loft 2] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:41:07 PM] [Sony Loft 2] Sony Loft 2: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:07 PM] [Sony Loft 1] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:41:07 PM] [Sony Loft 1] Sony Loft 1: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:16 PM] [Lounge TV] Getting inputs...
[3/22/2018, 1:41:16 PM] [Lounge TV] Found 4 HDMI inputs with 2 inserted CEC devices
[3/22/2018, 1:41:16 PM] [Lounge TV] Lounge TV: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:17 PM] [Sony Loft 2] Getting inputs...
[3/22/2018, 1:41:17 PM] [Sony Loft 1] Getting inputs...
[3/22/2018, 1:41:18 PM] [Sony Loft 2] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:41:18 PM] [Sony Loft 2] Sony Loft 2: Error: Callback was already called. - Trying again
[3/22/2018, 1:41:18 PM] [Sony Loft 1] Found 4 HDMI inputs with 0 inserted CEC devices
[3/22/2018, 1:41:18 PM] [Sony Loft 1] Sony Loft 1: Error: Callback was already called. - Trying again

Thank you I hope thats the log you are after

**Comment by seydx** [comment] 2018-03-22 14:35
thanks! should be fixed with 2.1.3!

**Comment by Philwh** [comment] 2018-03-22 14:40
Thank you again
